ZeeWebApp/Models/POEmployee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeeWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POEmployee
    {
        public int Id { get; set; }
        public Nullable<int> EntityID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string EmployeeID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<System.DateTime> LastWorkingDay { get; set; }
        public string Designation { get; set; }
        public string BloodGroup { get; set; }
        public string CompanyTransport { get; set; }
        public string Education { get; set; }
        public string VisaDesignation { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassportIssueDt { get; set; }
        public Nullable<System.DateTime> PassportExpiryDt { get; set; }
        public string PassportAtchmt { get; set; }
        public string VisaNo { get; set; }
        public Nullable<System.DateTime> VisaIssueDt { get; set; }
        public Nullable<System.DateTime> VisaExpiryDt { get; set; }
        public string VisaAtchmt { get; set; }
        public string UIDNo { get; set; }
        public string EmiratesIdNo { get; set; }
        public Nullable<System.DateTime> EmiratesIdIssueDt { get; set; }
        public Nullable<System.DateTime> EmiratesIdExpiryDt { get; set; }
        public string EmiratesIdAtchmt { get; set; }
        public string HouseFlatVillaNo { get; set; }
        public string StreetAreaName { get; set; }
        public string NearestLandmark { get; set; }
        public Nullable<int> ResidingEmirateID { get; set; }
        public string EmpMobNo { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactNumber { get; set; }
        public string EmergencyContactNameHmCtry { get; set; }
        public string EmergencyContactNumberHmCtry { get; set; }
        public string Email { get; set; }
        public string AddressHmCtry { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Emirate Emirate { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual Statustbl Statustbl { get; set; }
    }
}

ZeeWebApp/ViewModels/createviewmodel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using ZeeWebApp.Models;

namespace ZeeWebApp.ViewModels
{
    public class CreateViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Entity")]
        public int EntityID { get; set; }

        [Display(Name = "Status")]
        public int StatusID { get; set; }

        [Display(Name = "Employee ID")]
        public string EmployeeID { get; set; }

        [Display(Name = "Title")]
        public string Title { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Middle Name")]
        public string MiddleName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        public string Gender { get; set; }

        [Display(Name = "Marital Status")]
        public string MaritalStatus { get; set; }

        [Display(Name = "Nationality")]
        public int NationalityID { get; set; }

        [Display(Name = "Date of Joining")]
        public DateTime? DateOfJoining { get; set; }

        [Display(Name = "Last Working Day")]
        public DateTime? LastWorkingDay { get; set; }

        public string Designation { get; set; }

        [Display(Name = "Blood Group")]
        public string BloodGroup { get; set; }

        [Display(Name = "Company Transport")]
        public string CompanyTransport { get; set; }

        public string Education { get; set; }

        [Display(Name = "Visa Designation")]
        public string VisaDesignation { get; set; }

        [Display(Name = "Passport No")]
        public string PassportNo { get; set; }

        [Display(Name = "Passport Issue Date")]
        public DateTime? PassportIssueDt { get; set; }

        [Display(Name = "Passport Expiry Date")]
        public DateTime? PassportExpiryDt { get; set; }

        [Display(Name = "Passport Attachment")]
        public string PassportAtchmt { get; set; }

        [Display(Name = "Visa No")]
        public string VisaNo { get; set; }

        [Display(Name = "Visa Issue Date")]
        public DateTime? VisaIssueDt { get; set; }

        [Display(Name = "Visa Expiry Date")]
        public DateTime? VisaExpiryDt { get; set; }

        [Display(Name = "Visa Attachment")]
        public string VisaAtchmt { get; set; }

        [Display(Name = "UID No")]
        public string UIDNo { get; set; }

        [Display(Name = "Emirates Id No")]
        public string EmiratesIdNo { get; set; }

        [Display(Name = "Emirates Id Issue Date")]
        public DateTime? EmiratesIdIssueDt { get; set; }

        [Display(Name = "Emirates Id Expiry Date")]
        public DateTime? EmiratesIdExpiryDt { get; set; }

        [Display(Name = "Emirates Id Attachment")]
        public string EmiratesIdAtchmt { get; set; }

        [Display(Name = "House/Flat/Villa No")]
        public string HouseFlatVillaNo { get; set; }

        [Display(Name = "Street/Area Name")]
        public string StreetAreaName { get; set; }

        [Display(Name = "Nearest Landmark")]
        public string NearestLandmark { get; set; }

        [Display(Name = "Residing Emirate")]
        public int ResidingEmirateID { get; set; }

        [Display(Name = "Mobile No")]
        public string EmpMobNo { get; set; }

        [Display(Name = "Emergency Contact Name")]
        public string EmergencyContactName { get; set; }

        [Display(Name = "Emergency Contact No")]
        public string EmergencyContactNumber { get; set; }

        [Display(Name = "Emergency Contact Name (Home Country")]
        public string EmergencyContactNameHmCtry { get; set; }

        [Display(Name = "Emergency Contact No (Home Country)")]
        public string EmergencyContactNumberHmCtry { get; set; }

        [Display(Name = "Email Address")]
        public string Email { get; set; }

        [Display(Name = "Address (Home Country)")]
        public string AddressHmCtry { get; set; }

        public HttpPostedFileBase PassportAtchmtPath { get; set; }

        public virtual Country Country { get; set; }
        public virtual Emirate Emirate { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual Statustbl Statustbl { get; set; }
    }
}

ZeeWebApp/Controllers/POEmployeesController.cs
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ZeeWebApp.Models;
using ZeeWebApp.ViewModels;
using OfficeOpenXml;
using System.Configuration;
using System.IO;

namespace ZeeWebApp.Controllers
{
    [CustomErrorHandling]
    public class POEmployeesController : Controller
    {
        private MVC5DBContext db = new MVC5DBContext();

        // GET: Employees
        public ActionResult Index()
        {
            var poEmployees = db.POEmployees;

            ViewBag.EmpCreateSuccess = TempData["EmpCreateSuccess"] as bool?;
            ViewBag.EmpUpdateSuccess = TempData["EmpUpdateSuccess"] as bool?;

            return View(poEmployees.ToList());

        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            POEmployee poEmployee = db.POEmployees.Find(id);
            if (poEmployee == null)
            {
                return HttpNotFound();
            }
            return View(poEmployee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            POEmployeeCreateViewModel poEmpVM = new POEmployeeCreateViewModel();
            poEmpVM.StatusItems = new SelectList(db.Statustbls, "Id", "StatusVal");
            poEmpVM.ResidingEmirateItems = new SelectList(db.Emirates, "Id", "EmirateName");
            poEmpVM.NationalityItems = new SelectList(db.Countries, "Id", "Nationality");
            poEmpVM.EntityItems = new SelectList(db.Entities, "Id", "EntityName");

            return View(poEmpVM);
        }
        
        [HttpPost]
        public ActionResult Create(POEmployeeCreateViewModel poEmployee)
        {
            POEmployee poEmp = new POEmployee(); 

            if (string.IsNullOrEmpty(poEmployee.FirstName))
            {
                ModelState.AddModelError("Name", "The first name is required. Kindly enter a first name.");
            }

            if (ModelState.IsValid)
            {
                //check file uploads
                if (poEmployee.PassportAtchmtObj != null)
                {
                    poEmployee.PassportAtchmt = SaveFileToSystem(poEmployee.PassportAtchmtObj);
                }

                if (poEmployee.VisaAtchmtObj != null)
                {
                    poEmployee.VisaAtchmt = SaveFileToSystem(poEmployee.VisaAtchmtObj);
                }

                if (poEmployee.EmrtsIdAtchmtObj != null)
                {
                    poEmployee.EmiratesIdAtchmt = SaveFileToSystem(poEmployee.EmrtsIdAtchmtObj);
                }

                //poEmp = poEmployee;
                poEmp.Title = poEmployee.Title;
                poEmp.FirstName = poEmployee.FirstName;
                poEmp.MiddleName = poEmployee.MiddleName;
                poEmp.LastName = poEmployee.LastName;
                poEmp.EntityID = poEmployee.EntityID;
                poEmp.StatusID = poEmployee.StatusID;
                poEmp.EmployeeID = poEmployee.EmployeeID;
                poEmp.Gender = poEmployee.Gender;
                poEmp.MaritalStatus = poEmployee.MaritalStatus;
                poEmp.NationalityID = poEmployee.NationalityID;
                poEmp.DateOfJoining = poEmployee.DateOfJoining;
                poEmp.LastWorkingDay = poEmployee.LastWorkingDay;
                poEmp.Designation = poEmployee.Designation;
                poEmp.BloodGroup = poEmployee.BloodGroup;
                poEmp.CompanyTransport = poEmployee.CompanyTransport;
                poEmp.Education = poEmployee.Education;
                poEmp.VisaDesignation = poEmployee.VisaDesignation;
                poEmp.PassportNo = poEmployee.PassportNo;
                poEmp.PassportIssueDt = poEmployee.PassportIssueDt;
                poEmp.PassportExpiryDt = poEmployee.PassportExpiryDt;
                poEmp.PassportAtchmt = poEmployee.PassportAtchmt;
                poEmp.VisaNo = poEmployee.VisaNo;
                poEmp.VisaIssueDt = poEmployee.VisaIssueDt;
                poEmp.VisaExpiryDt = poEmployee.VisaExpiryDt;
                poEmp.VisaAtchmt = poEmployee.VisaAtchmt;
                poEmp.UIDNo = poEmployee.UIDNo;
                poEmp.EmiratesIdNo = poEmployee.EmiratesIdNo;
                poEmp.EmiratesIdIssueDt = poEmployee.EmiratesIdIssueDt;
                poEmp.EmiratesIdExpiryDt = poEmployee.EmiratesIdExpiryDt;
                poEmp.EmiratesIdAtchmt = poEmployee.EmiratesIdAtchmt;
                poEmp.HouseFlatVillaNo = poEmployee.HouseFlatVillaNo;
                poEmp.StreetAreaName = poEmployee.StreetAreaName;
                poEmp.NearestLandmark = poEmployee.NearestLandmark;
                poEmp.ResidingEmirateID = poEmployee.ResidingEmirateID;
                poEmp.EmpMobNo = poEmployee.EmpMobNo;
                poEmp.EmergencyContactName = poEmployee.EmergencyContactName;
                poEmp.EmergencyContactNumber = poEmployee.EmergencyContactNumber;
                poEmp.EmergencyContactNameHmCtry = poEmployee.EmergencyContactNameHmCtry;
                poEmp.EmergencyContactNumberHmCtry = poEmployee.EmergencyContactNumberHmCtry;
                poEmp.Email = poEmployee.Email;
                poEmp.AddressHmCtry = poEmployee.AddressHmCtry;

                db.POEmployees.Add(poEmp);
                db.SaveChanges();
                TempData["EmpCreateSuccess"] = true;
                return RedirectToAction("Index");
            }
            else
            {
                var errors = ModelState.Select(x => x.Value.Errors)
                           .Where(y => y.Count > 0)
                           .ToList();
            }

            //POEmployeeCreateViewModel poEmpVM = new POEmployeeCreateViewModel();
            poEmployee.StatusItems = new SelectList(db.Statustbls, "Id", "StatusVal", poEmployee.StatusID);
            poEmployee.ResidingEmirateItems = new SelectList(db.Emirates, "Id", "EmirateName", poEmployee.ResidingEmirateID);
            poEmployee.NationalityItems = new SelectList(db.Countries, "Id", "Nationality", poEmployee.NationalityID);
            poEmployee.EntityItems = new SelectList(db.Entities, "Id", "EntityName", poEmployee.EntityID);

            return View(poEmployee);
        }

        // FILE SAVE METHOD
        private string SaveFileToSystem(HttpPostedFileBase fileObj)
        {
            string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(fileObj.FileName);
            string extension = Path.GetExtension(fileObj.FileName);
            string filename = fileNameWithoutExtension + DateTime.Now.ToString("yyyy'-'MM'-'dd'T'HH'-'mm'-'ss") + extension;

            string savepath = Server.MapPath("~/UploadedFiles/");
            string fullfilepath = Path.Combine(savepath, filename);
            fileObj.SaveAs(fullfilepath); //save the actual file to the file system

            return "/UploadedFiles/" + filename; //save the URL value to model/db
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            POEmployee poemp = new POEmployee();
            POEmployeeEditViewModel poEmpVM = new POEmployeeEditViewModel();

            poemp = db.POEmployees.Find(id);

            poEmpVM.Title = poemp.Title;
            poEmpVM.FirstName = poemp.FirstName;
            poEmpVM.MiddleName = poemp.MiddleName;
            poEmpVM.LastName = poemp.LastName;
            poEmpVM.EntityID = poemp.EntityID;
            poEmpVM.StatusID = poemp.StatusID;
            poEmpVM.EmployeeID = poemp.EmployeeID;
            poEmpVM.Gender = poemp.Gender;
            poEmpVM.MaritalStatus = poemp.MaritalStatus;
            poEmpVM.NationalityID = poemp.NationalityID;
            poEmpVM.DateOfJoining = poemp.DateOfJoining;
            poEmpVM.LastWorkingDay = poemp.LastWorkingDay;
            poEmpVM.Designation = poemp.Designation;
            poEmpVM.BloodGroup = poemp.BloodGroup;
            poEmpVM.CompanyTransport = poemp.CompanyTransport;
            poEmpVM.Education = poemp.Education;
            poEmpVM.VisaDesignation = poemp.VisaDesignation;
            poEmpVM.PassportNo = poemp.PassportNo;
            poEmpVM.PassportIssueDt = poemp.PassportIssueDt;
            poEmpVM.PassportExpiryDt = poemp.PassportExpiryDt;
            poEmpVM.PassportAtchmt = poemp.PassportAtchmt;
            poEmpVM.VisaNo = poemp.VisaNo;
            poEmpVM.VisaIssueDt = poemp.VisaIssueDt;
            poEmpVM.VisaExpiryDt = poemp.VisaExpiryDt;
            poEmpVM.VisaAtchmt = poemp.VisaAtchmt;
            poEmpVM.UIDNo = poemp.UIDNo;
            poEmpVM.EmiratesIdNo = poemp.EmiratesIdNo;
            poEmpVM.EmiratesIdIssueDt = poemp.EmiratesIdIssueDt;
            poEmpVM.EmiratesIdExpiryDt = poemp.EmiratesIdExpiryDt;
            poEmpVM.EmiratesIdAtchmt = poemp.EmiratesIdAtchmt;
            poEmpVM.HouseFlatVillaNo = poemp.HouseFlatVillaNo;
            poEmpVM.StreetAreaName = poemp.StreetAreaName;
            poEmpVM.NearestLandmark = poemp.NearestLandmark;
            poEmpVM.ResidingEmirateID = poemp.ResidingEmirateID;
            poEmpVM.EmpMobNo = poemp.EmpMobNo;
            poEmpVM.EmergencyContactName = poemp.EmergencyContactName;
            poEmpVM.EmergencyContactNumber = poemp.EmergencyContactNumber;
            poEmpVM.EmergencyContactNameHmCtry = poemp.EmergencyContactNameHmCtry;
            poEmpVM.EmergencyContactNumberHmCtry = poemp.EmergencyContactNumberHmCtry;
            poEmpVM.Email = poemp.Email;
            poEmpVM.AddressHmCtry = poemp.AddressHmCtry;

            //populate the dropdownlists with the selected values from employee

ZeeWebApp/Views/POEmployees/Index.cshtml
@model IEnumerable<ZeeWebApp.Models.POEmployee>

@{
    ViewBag.Title = "List of All Employees";
}

<h2>List of All Employees</h2>

<table id="POEmployeesIndex" class="table table-striped table-bordered">
    <thead>        
        <tr>
            <th style="display:none;">
                @Html.DisplayNameFor(model => model.First().Id)
            </th>
            <th style="display:none;">
                @Html.DisplayNameFor(model => model.First().EntityID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().StatusID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().EmployeeID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().MiddleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Country.Nationality)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().PassportNo)
            </th>
            <th>Actions</th>
            <th style="display:none;">
                @Html.DisplayNameFor(model => model.First().PassportExpiryDt)
            </th>
            <th style="display:none;">
                @Html.DisplayNameFor(model => model.First().VisaExpiryDt)
            </th>
            <th style="display:none;">
                @Html.DisplayNameFor(model => model.First().EmiratesIdExpiryDt)
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="9"> There are no results!</td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
    <tr>
        <td style="display:none;">
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td style="display:none;">
            @Html.DisplayFor(modelItem => item.Entity.EntityName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Statustbl.StatusVal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmployeeID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MiddleName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country.Nationality)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PassportNo)
        </td>
        <td>
            <a href="@Url.Action("Details", "POEmployees", new { id = item.Id })"><span class="me-1"><i class="bi bi-eye"></i></span></a>

            @if (User.IsInRole("Admin"))
            {
                <a href="@Url.Action("Edit", "POEmployees", new { id = item.Id })"><span class="me-1"><i class="bi bi-pencil-square"></i></span></a>
                <a href="@Url.Action("Delete", "POEmployees", new { id = item.Id })"><span class="me-1"><i class="bi bi-trash3"></i></span></a>
                <input type="button" class="btnRowDelete"><span class="me-1" />

        }
</td>
        <td style="display:none;">
            @Html.DisplayFor(modelItem => item.PassportExpiryDt)
        </td>
        <td style="display:none;">
            @Html.DisplayFor(modelItem => item.VisaExpiryDt)
        </td>
        <td style="display:none;">
            @Html.DisplayFor(modelItem => item.EmiratesIdExpiryDt)
        </td>
    </tr>
            }
        }
           </tbody>
    <tfoot>
        <tr>
            <th style="display:none;">
                @Html.DisplayNameFor(model => model.First().Id)
            </th>
            <th style="display:none;">
                @Html.DisplayNameFor(model => model.First().EntityID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().StatusID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().EmployeeID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().MiddleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Country.Nationality)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().PassportNo)
            </th>
            <th>Actions</th>
            <th style="display:none;">
                @Html.DisplayNameFor(model => model.First().PassportExpiryDt)
            </th>
            <th style="display:none;">
                @Html.DisplayNameFor(model => model.First().VisaExpiryDt)
            </th>
            <th style="display:none;">
                @Html.DisplayNameFor(model => model.First().EmiratesIdExpiryDt)
            </th>
        </tr>
    </tfoot>
</table>


<p>
    
    @if (User.IsInRole("Admin"))
    {
        <a href="@Url.Action("Create", "POEmployees")" class="btn btn-light"><span class="me-2"><i class="bi bi-person-plus-fill"></i></span><span>Create New</span></a>
    }
        @*<a href="@Url.Action("DownloadExcel", "POEmployees")" class="btn btn-primary"><span class="me-2"><i class="bi bi-download"></i></span><span>Export to Excel</span></a>*@

    </p>

<div id="testdiv">
    <input class="btn btn-primary" name="submittestButton" id="btntestSave" value="testSave" type="button">
</div>

@section scripts {
    <script>
        $(document).ready(function () {

            // show when page load
            //debugger
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": false,
                "progressBar": false,
                "positionClass": "toast-bottom-full-width",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "3000",
                "hideDuration": "1000",
                "timeOut": "3000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }

            if (Boolean("@ViewBag.EmpCreateSuccess")) {
                toastr.success("The Employee was added successfully!");
            }
            else if (Boolean("@ViewBag.EmpUpdateSuccess")) {
                toastr.success("The Employee was updated successfully!");
            }

            //TABLE ROW DELETE BUTTON CLICK EVENT

            $('.btnRowDelete').click(function (e) {
                debugger
                e.preventDefault();
                var POEmpId = $(this).closest('tr').find('td').eq(0).text().trim();
                $.ajax({
                type: "POST",
                    url: "/POEmployees/Delete",
                    contentType: "application/json; charset=utf-8",
                    ajaxasync: true,
                    data: '{id: "' + POEmpId + '" }',
                //data: { id: POEmpId },
                    success: function (result) {
                        alert("yes");
                        alert('Yay! It worked!tim' + result);
                },
                error: function (error) {
                    alert("Error");
                }
                });


             });



            //TEST AJAX


            $("#btntestSave").click(function () {
                debugger
            alert("test btn clicked!");
            var id = "lala";
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("testajax", "POEmployees")',
                    data: '{id: "' + id + '" }',
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    alert("Data has been added successfully." + response);
                    //LoadData();
                },
                    error: function (response) {
                        alert("Error while inserting data" + response);
                }
            });
            return false;
        });















            //ADD ADDITIONAL BOOTRAP CLASS TO PAGINATION HTML CODE SINCE PagedList DOESNT PROVED CSS SUPPORT FOR BOOTSTRAP 4 and HIGHER
            //var element = document.getElementsByClassName("page-item");
            //for (var i = 0; i < element.length; i++) {
            //    var aElementinLi = element[i].getElementsByTagName("a");
            //    aElementinLi[0].classList.add("page-link");
            //}



        });
    </script>
}