ZeeWebApp/Models/Employee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeeWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public int DepartmentID { get; set; }
        public string email { get; set; }
    
        public virtual Department Department { get; set; }
    }
}

ZeeWebApp/ViewModels/createviewmodel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using ZeeWebApp.Models;

namespace ZeeWebApp.ViewModels
{
    public class CreateViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Entity")]
        public int EntityID { get; set; }

        [Display(Name = "Status")]
        public int StatusID { get; set; }

        [Display(Name = "Employee ID")]
        public string EmployeeID { get; set; }

        [Display(Name = "Title")]
        public string Title { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Middle Name")]
        public string MiddleName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        public string Gender { get; set; }

        [Display(Name = "Marital Status")]
        public string MaritalStatus { get; set; }

        [Display(Name = "Nationality")]
        public int NationalityID { get; set; }

        [Display(Name = "Date of Joining")]
        public DateTime? DateOfJoining { get; set; }

        [Display(Name = "Last Working Day")]
        public DateTime? LastWorkingDay { get; set; }

        public string Designation { get; set; }

        [Display(Name = "Blood Group")]
        public string BloodGroup { get; set; }

        [Display(Name = "Company Transport")]
        public string CompanyTransport { get; set; }

        public string Education { get; set; }

        [Display(Name = "Visa Designation")]
        public string VisaDesignation { get; set; }

        [Display(Name = "Passport No")]
        public string PassportNo { get; set; }

        [Display(Name = "Passport Issue Date")]
        public DateTime? PassportIssueDt { get; set; }

        [Display(Name = "Passport Expiry Date")]
        public DateTime? PassportExpiryDt { get; set; }

        [Display(Name = "Passport Attachment")]
        public string PassportAtchmt { get; set; }

        [Display(Name = "Visa No")]
        public string VisaNo { get; set; }

        [Display(Name = "Visa Issue Date")]
        public DateTime? VisaIssueDt { get; set; }

        [Display(Name = "Visa Expiry Date")]
        public DateTime? VisaExpiryDt { get; set; }

        [Display(Name = "Visa Attachment")]
        public string VisaAtchmt { get; set; }

        [Display(Name = "UID No")]
        public string UIDNo { get; set; }

        [Display(Name = "Emirates Id No")]
        public string EmiratesIdNo { get; set; }

        [Display(Name = "Emirates Id Issue Date")]
        public DateTime? EmiratesIdIssueDt { get; set; }

        [Display(Name = "Emirates Id Expiry Date")]
        public DateTime? EmiratesIdExpiryDt { get; set; }

        [Display(Name = "Emirates Id Attachment")]
        public string EmiratesIdAtchmt { get; set; }

        [Display(Name = "House/Flat/Villa No")]
        public string HouseFlatVillaNo { get; set; }

        [Display(Name = "Street/Area Name")]
        public string StreetAreaName { get; set; }

        [Display(Name = "Nearest Landmark")]
        public string NearestLandmark { get; set; }

        [Display(Name = "Residing Emirate")]
        public int ResidingEmirateID { get; set; }

        [Display(Name = "Mobile No")]
        public string EmpMobNo { get; set; }

        [Display(Name = "Emergency Contact Name")]
        public string EmergencyContactName { get; set; }

        [Display(Name = "Emergency Contact No")]
        public string EmergencyContactNumber { get; set; }

        [Display(Name = "Emergency Contact Name (Home Country")]
        public string EmergencyContactNameHmCtry { get; set; }

        [Display(Name = "Emergency Contact No (Home Country)")]
        public string EmergencyContactNumberHmCtry { get; set; }

        [Display(Name = "Email Address")]
        public string Email { get; set; }

        [Display(Name = "Address (Home Country)")]
        public string AddressHmCtry { get; set; }

        public HttpPostedFileBase PassportAtchmtPath { get; set; }

        public virtual Country Country { get; set; }
        public virtual Emirate Emirate { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual Statustbl Statustbl { get; set; }
    }
}

ZeeWebApp/Controllers/EmployeesController.cs
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ZeeWebApp.Models;

namespace ZeeWebApp.Controllers
{
    [Authorize(Roles ="Admin, Student, Faculty")]
    public class EmployeesController : Controller
    {
        private MVC5DBContext db = new MVC5DBContext();

        // GET: Employees
        public ActionResult Index(string searchBy, string searchText, int? page, string sortBy)
        {
            ViewBag.SortNameParameter = string.IsNullOrEmpty(sortBy) ? "Name desc" : "";
            ViewBag.SortGenderParameter = sortBy == "Gender" ? "Gender Desc" : "Gender";

            //var employees = db.Employees.Include(e => e.Department);

            var employees = db.Employees.AsQueryable();

            if (searchBy == "Gender")
            {

                employees = employees.Where(x => x.Gender.Trim() == searchText || searchText == null);
            }
            else
            {

                employees = employees.Where(x => x.Name.Trim().StartsWith(searchText) || searchText == null);
            }

            switch(sortBy)
            {
                case "Name desc":
                    employees = employees.OrderByDescending(x => x.Name);
                    break;
                case "Gender Desc":
                    employees = employees.OrderByDescending(x => x.Gender);
                    break;
                case "Gender":
                    employees = employees.OrderBy(x => x.Gender);
                    break;
                default:
                    employees = employees.OrderBy(x => x.Name);
                    break;
            }

            return View(employees.ToPagedList(page ?? 1, 5));
            
        }

        [HttpPost]
        public ActionResult DeleteFromListofEmps(IEnumerable<int> employeeIdsToDelete)
        {
            db.Employees.Where(x => employeeIdsToDelete.Contains(x.EmployeeID))
                .ToList()
                .ForEach(y => db.Employees.Remove(y));
            db.SaveChanges();
            
           return RedirectToAction("Index");
        }
        public ActionResult EmployeesByDepartment()
        {
            var employees = db.Employees.Include(e => e.Department)
                                .GroupBy(x => x.Department.Name)
                                .Select(y => new DepartmentTotals
                                 {
                                     Name = y.Key,
                                     Total = y.Count()
                                 }).ToList(); ;
            return View(employees);
        }

        // GET: Employees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentID = new SelectList(db.Departments, "Id", "Name");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmployeeID,Name,Gender,City,DepartmentID")] Employee employee)
        {
            if(string.IsNullOrEmpty(employee.Name))
            {
                ModelState.AddModelError("Name","Bruh, the name is requried! Enter a name!");
            }
            if (ModelState.IsValid)
            {
                db.Employees.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DepartmentID = new SelectList(db.Departments, "Id", "Name", employee.DepartmentID);
            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            employee.Gender = employee.Gender.Trim(); //remove whitespace from the retrieved string
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepartmentID = new SelectList(db.Departments, "Id", "Name", employee.DepartmentID);
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Exclude = "Name")] Employee employee)
        {
            Employee EmployeeFromDB = db.Employees.Single(x => x.EmployeeID == employee.EmployeeID);
            EmployeeFromDB.Gender = employee.Gender;
            EmployeeFromDB.City = employee.City;
            EmployeeFromDB.DepartmentID = employee.DepartmentID;
            employee.Name = EmployeeFromDB.Name;

            if (ModelState.IsValid)
            {
                db.Entry(EmployeeFromDB).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DepartmentID = new SelectList(db.Departments, "Id", "Name", employee.DepartmentID);
            return View(employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = db.Employees.Find(id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZeeWebApp/Views/Employees/Create.cshtml
@model ZeeWebApp.Models.Employee

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Gender", new List<SelectListItem>
                {
                new SelectListItem { Text = "Male", Value="Male" },
                new SelectListItem { Text = "Female", Value="Female" }
                }, "Select Gender", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentID, "Department", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmentID", null,"Select Department", htmlAttributes: new { @class = "form-control" })                
                @Html.ValidationMessageFor(model => model.DepartmentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ZeeWebApp/Views/Employees/Delete.cshtml
@model ZeeWebApp.Models.Employee

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ZeeWebApp/Views/Employees/Details.cshtml
@model ZeeWebApp.Models.Employee

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EmployeeID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ZeeWebApp/Views/Employees/Edit.cshtml
@model ZeeWebApp.Models.Employee

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EmployeeID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.HiddenFor(model => model.Name)*@
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.DisplayFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("Gender", new List<SelectListItem>
                {
                new SelectListItem { Text = "Male", Value="Male" },
                new SelectListItem { Text = "Female", Value="Female" }
                }, "Select Gender", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentID, "Department", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmentID", null, "Select Department", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartmentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ZeeWebApp/Views/Employees/EmployeesByDepartment.cshtml
@model IEnumerable<ZeeWebApp.Models.DepartmentTotals>

@{
    ViewBag.Title = "EmployeesByDepartment";
}

<h2>EmployeesByDepartment</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Total)
    </td>
</tr>
}

</table>

ZeeWebApp/Views/Employees/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<ZeeWebApp.Models.Employee>

@{
    ViewBag.Title = "List of Employees";
}

<h2>List of Employees</h2>

@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

    <p>
        @using (Html.BeginForm("Index", "Employees", FormMethod.Get))
        {
            <b>Search By:</b>
            @Html.RadioButton("searchBy", "Name", true) <text>Name</text>
            @Html.RadioButton("searchBy", "Gender") <text>Gender</text><br />

            @Html.TextBox("searchText") <input type="submit" value="Search!" />
        }


    </p>
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Name", "Index", new { sortBy = ViewBag.SortNameParameter, searchBy = Request.QueryString["searchBy"], searchText = Request.QueryString["searchText"] })
            </th>
            <th>
                @Html.ActionLink("Gender", "Index", new { sortBy = ViewBag.SortGenderParameter, searchBy = Request.QueryString["searchBy"], searchText = Request.QueryString["searchText"] })
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Department.Name)
            </th>
            <th></th>
        </tr>

        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4"> There aren't any results bro!</td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gender)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Department.Name)
                    </td>
                    <td>
                        @if (User.IsInRole("Admin"))
                        {
                            @Html.ActionLink("Edit", "Edit", new { id = item.EmployeeID }) <text>|</text>
                            @Html.ActionLink("Delete", "Delete", new { id = item.EmployeeID }) <text>|</text>
                        }

                        @Html.ActionLink("Details", "Details", new { id = item.EmployeeID })
                    </td>
                </tr>
            }
        }

    </table>

    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, searchBy = Request.QueryString["searchBy"], searchText = Request.QueryString["searchText"], sortBy = Request["sortBy"] }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayItemSliceAndTotal = true })