ZeeWebApp/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ZeeWebApp.Models;

namespace ZeeWebApp.Controllers
{
    public class AccountsController : Controller
    {
        // GET: Accounts
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(User model)
        {
            using (MVC5DBContext context = new MVC5DBContext())
            {
                bool IsValidUser = context.Users.Any(user => user.username.ToLower() ==
                     model.username.ToLower() && user.pwd == model.pwd);
                if (IsValidUser)
                {
                    FormsAuthentication.SetAuthCookie(model.username, false);
                    return RedirectToAction("Index", "POEmployees");
                }
                ModelState.AddModelError("", "invalid Username or Password");
                return View();
            }
        }

        public ActionResult Signup()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Signup(User model)
        {
            using (MVC5DBContext context = new MVC5DBContext())
            {
                context.Users.Add(model);
                context.SaveChanges();
            }

            return RedirectToAction("Login");
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

ZeeWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - HR Management System - University of Stirling RAK Campus</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.bootstrap5.min.css" />    
    @Styles.Render("https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css")
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    @Scripts.Render("~/bundles/modernizr")


</head>
<body>
    <!-- NAVBAR MENU-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <div class="container-fluid">
            <!-- Offcanvas trigger-->
            <button class="navbar-toggler me-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
                <span class="navbar-toggler-icon" data-bs-target="#offcanvasExample"></span>
            </button>
            <!-- Offcanvas trigger-->
            <a class="navbar-brand fw-bold me-auto" href="#">HR Management System</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                @*<ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    @Html.ActionLink("Home", "Index", "Home", htmlAttributes: new { @class = "nav-link" })
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Link</a>
                                </li>
                                <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Dropdown
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>*@
                @*<li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                    </ul>*@
                <form class="d-flex ms-auto">
                    <ul class="navbar-nav mb-2 mb-lg-0">
                        @if (User.Identity.IsAuthenticated)
                        {


                            @*if (User.IsInRole("Admin") || User.IsInRole("Faculty"))
                                {
                                    <li>@Html.ActionLink("Create Employee", "Create", "POEmployees", htmlAttributes: new { @class = "nav-link" })</li>
                                }*@

                            <li class="nav-item"><a class="nav-link my-1 my-lg-0">Hello - @User.Identity.Name</a></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-person-fill"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <li>@Html.ActionLink("Logout", "Logout", "Accounts", null, htmlAttributes: new { @class = "dropdown-item" })</li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            @*<li class="nav-item"><a class="nav-link">Hello - Zeeshan!</a></li>*@
                            <li class="nav-item">@Html.ActionLink("Login", "Login", "Accounts", null, htmlAttributes: new { @class = "nav-link my-1 my-lg-0" })</li>
                        }
                    </ul>
                    @*<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>*@
                </form>
            </div>
        </div>
    </nav>
    <!-- NAVBAR MENU-->
    <!-- OFFCANVAS MENU-->
    @*<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
            Link with href
        </a>*@


    <div class="offcanvas offcanvas-start sidebar-nav" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
        @*<div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasExampleLabel">Offcanvas</h5>
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>*@
        <div class="offcanvas-body p-0">
            <nav>
                <ul class="navbar-nav">
                    <li>
                        <div class="text-muted small fw-bold text-uppercase px-3">
                            CORE
                        </div>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Home")" class="nav-link px-3"><span class="me-2"><i class="bi bi-speedometer"></i></span><span>Dashboard</span></a>
                    </li>
                    <li class="my-4">
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <div class="text-muted small fw-bold text-uppercase px-3">
                            EMPLOYEE MODULE
                        </div>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "POEmployees")" class="nav-link px-3"><span class="me-2"><i class="bi bi-card-list"></i></span><span>Employees List</span></a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin") || User.IsInRole("Faculty"))
                        {
                            <li>
                                <a href="@Url.Action("Create", "POEmployees")" class="nav-link px-3"><span class="me-2"><i class="bi bi-textarea-t"></i></span><span>Create Employee</span></a>
                            </li>
                        }
                    }
                </ul>
            </nav>

        </div>
    </div>

    <!-- OFFCANVAS MENU-->
    @*<main class="mt-5 pt-3">

        </main>*@

    <main class="mt-5 pt-3">
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - HR Management System - University of Stirling RAK Campus</p>
            </footer>
        </div>
    </main>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js")
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.print.min.js"></script>
    
    <script src="~/Scripts/WebAppScripts.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>